2024-11-12 16:34:08,965 - ERROR: Task exception was never retrieved
future: <Task finished name='Task-230' coro=<AsyncServer._handle_event_internal() done, defined at C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\socketio\async_server.py:608> exception=TypeError('a coroutine was expected, got None')>
Traceback (most recent call last):
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\socketio\async_server.py", line 610, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\socketio\async_server.py", line 637, in _trigger_event
    ret = await handler(*args)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\UserInterface\StaffUI.py", line 245, in handle_add_virtual_vehicle
    name = environment_mng.add_virtual_vehicle()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\EnvironmentManagement\EnvironmentManager.py", line 676, in add_virtual_vehicle
    self.botTest = Bot(new_vehicle, self._behaviour_ctrl)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\BotManagement\Bot.py", line 10, in __init__
    asyncio.create_task(self.test())
  File "C:\Users\mariok\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 374, in create_task
    task = loop.create_task(coro)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 436, in create_task
    task = tasks.Task(coro, loop=self, name=name, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: a coroutine was expected, got None
2024-11-12 16:34:10,525 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.HACKING_PROTECTION
2024-11-12 16:34:10,526 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.CLEAN_HACKED_EFFECTS
2024-11-12 16:34:10,986 - DEBUG: 19 BLE-Devices found
2024-11-12 16:34:43,328 - INFO: -------------------------
2024-11-12 16:34:43,329 - INFO:  STARTING IAV-Distortion 
2024-11-12 16:34:43,330 - INFO: -------------------------
2024-11-12 16:34:43,343 - INFO: Auto discovery service for Anki cars activated.
2024-11-12 16:34:43,420 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-12 16:34:43,617 - ERROR: Invalid session wCrAxuW8ZjsRjSkRAAAA (further occurrences of this error will be logged with level INFO)
2024-11-12 16:34:44,039 - ERROR: Invalid transport for session C34eiHMJLkQjX0lNAAAA (further occurrences of this error will be logged with level INFO)
2024-11-12 16:34:48,432 - DEBUG: 17 BLE-Devices found
2024-11-12 16:34:48,759 - ERROR: Task exception was never retrieved
future: <Task finished name='Task-285' coro=<Bot.test() done, defined at C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\BotManagement\Bot.py:13> exception=TypeError("object int can't be used in 'await' expression")>
Traceback (most recent call last):
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\BotManagement\Bot.py", line 14, in test
    await(1)
TypeError: object int can't be used in 'await' expression
2024-11-12 16:35:13,944 - INFO: Player 91bbb946-a49c-43ce-a0fd-2a71ee20447b timed out. Removing player from the game...
2024-11-12 16:35:53,461 - DEBUG: 17 BLE-Devices found
2024-11-12 16:36:06,507 - INFO: -------------------------
2024-11-12 16:36:06,507 - INFO:  STARTING IAV-Distortion 
2024-11-12 16:36:06,508 - INFO: -------------------------
2024-11-12 16:36:06,519 - INFO: Auto discovery service for Anki cars activated.
2024-11-12 16:36:06,596 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-12 16:36:06,921 - ERROR: Invalid transport for session gmCO2jtUKo1xUAuAAAAA (further occurrences of this error will be logged with level INFO)
2024-11-12 16:36:11,596 - DEBUG: 18 BLE-Devices found
2024-11-12 16:36:34,820 - INFO: -------------------------
2024-11-12 16:36:34,821 - INFO:  STARTING IAV-Distortion 
2024-11-12 16:36:34,822 - INFO: -------------------------
2024-11-12 16:36:34,836 - INFO: Auto discovery service for Anki cars activated.
2024-11-12 16:36:34,930 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-12 16:36:35,093 - ERROR: Invalid session qSKJhJLCEVzTDI8ZAAAB (further occurrences of this error will be logged with level INFO)
2024-11-12 16:36:36,071 - ERROR: Invalid transport for session LRkwlbYEgq-10fTZAAAA (further occurrences of this error will be logged with level INFO)
2024-11-12 16:36:38,566 - ERROR: Task exception was never retrieved
future: <Task finished name='Task-130' coro=<Bot.test() done, defined at C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\BotManagement\Bot.py:13> exception=NameError("name 'true' is not defined")>
Traceback (most recent call last):
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\BotManagement\Bot.py", line 14, in test
    while(true):
          ^^^^
NameError: name 'true' is not defined
2024-11-12 16:36:39,936 - DEBUG: 18 BLE-Devices found
2024-11-12 16:36:49,321 - INFO: -------------------------
2024-11-12 16:36:49,321 - INFO:  STARTING IAV-Distortion 
2024-11-12 16:36:49,322 - INFO: -------------------------
2024-11-12 16:36:49,332 - INFO: Auto discovery service for Anki cars activated.
2024-11-12 16:36:49,423 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-12 16:36:49,445 - ERROR: Invalid session LRkwlbYEgq-10fTZAAAA (further occurrences of this error will be logged with level INFO)
2024-11-12 16:36:50,008 - ERROR: Invalid transport for session 7CVFm6GLtsSks7nWAAAA (further occurrences of this error will be logged with level INFO)
2024-11-12 16:36:54,430 - DEBUG: 19 BLE-Devices found
2024-11-12 16:37:35,793 - INFO: -------------------------
2024-11-12 16:37:35,793 - INFO:  STARTING IAV-Distortion 
2024-11-12 16:37:35,794 - INFO: -------------------------
2024-11-12 16:37:35,804 - INFO: Auto discovery service for Anki cars activated.
2024-11-12 16:37:35,874 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-12 16:37:37,889 - ERROR: Invalid transport for session xzrCzxZYrkflFzmAAAAA (further occurrences of this error will be logged with level INFO)
2024-11-12 16:37:40,879 - DEBUG: 14 BLE-Devices found
2024-11-12 16:38:53,370 - INFO: -------------------------
2024-11-12 16:38:53,371 - INFO:  STARTING IAV-Distortion 
2024-11-12 16:38:53,371 - INFO: -------------------------
2024-11-12 16:38:53,380 - INFO: Auto discovery service for Anki cars activated.
2024-11-12 16:38:53,470 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-12 16:38:56,047 - ERROR: Invalid transport for session m_DVuYmctkjJ2TIcAAAA (further occurrences of this error will be logged with level INFO)
2024-11-12 16:38:58,474 - DEBUG: 16 BLE-Devices found
2024-11-12 16:41:52,666 - INFO: -------------------------
2024-11-12 16:41:52,667 - INFO:  STARTING IAV-Distortion 
2024-11-12 16:41:52,668 - INFO: -------------------------
2024-11-12 16:41:52,677 - INFO: Auto discovery service for Anki cars activated.
2024-11-12 16:41:52,753 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-12 16:41:53,012 - ERROR: post request handler error
Traceback (most recent call last):
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\engineio\async_server.py", line 316, in handle_request
    await socket.handle_post_request(environ)
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\engineio\async_socket.py", line 109, in handle_post_request
    p = payload.Payload(encoded_payload=body)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\engineio\payload.py", line 13, in __init__
    self.decode(encoded_payload)
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\engineio\payload.py", line 44, in decode
    raise ValueError('Too many packets in payload')
ValueError: Too many packets in payload
2024-11-12 16:41:53,076 - ERROR: Invalid transport for session ajlBpEADuwi99en-AAAA (further occurrences of this error will be logged with level INFO)
2024-11-12 16:41:57,739 - DEBUG: 14 BLE-Devices found
2024-11-12 16:42:06,305 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.HACKING_PROTECTION
2024-11-12 16:42:06,305 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.CLEAN_HACKED_EFFECTS
2024-11-12 16:42:10,865 - ERROR: Exception on request GET /driver/
Traceback (most recent call last):
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\quart\app.py", line 1403, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\quart\app.py", line 1441, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\quart\app.py", line 1029, in handle_user_exception
    raise error
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\quart\app.py", line 1439, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\quart\app.py", line 1535, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\UserInterface\DriverUI.py", line 77, in home_driver
    player_exists, picture, vehicle_information = self._prepare_html_data(player)
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\UserInterface\DriverUI.py", line 357, in _prepare_html_data
    self.environment_mng.put_player_on_next_free_spot(player)
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\EnvironmentManagement\EnvironmentManager.py", line 276, in put_player_on_next_free_spot
    result = self._assign_players_to_vehicles()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\EnvironmentManagement\EnvironmentManager.py", line 301, in _assign_players_to_vehicles
    self.botTest.stop()
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\BotManagement\Bot.py", line 19, in stop
    if self._task:
      ^^^^^^^^^^
AttributeError: 'Bot' object has no attribute '_task'
2024-11-14 10:27:10,560 - INFO: -------------------------
2024-11-14 10:27:10,562 - INFO:  STARTING IAV-Distortion 
2024-11-14 10:27:10,563 - INFO: -------------------------
2024-11-14 10:27:10,579 - INFO: Auto discovery service for Anki cars activated.
2024-11-14 10:27:10,758 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-14 10:27:15,780 - DEBUG: 14 BLE-Devices found
2024-11-14 10:27:19,869 - ERROR: Invalid transport for session IB8kR9b_jSjXR4xpAAAA (further occurrences of this error will be logged with level INFO)
2024-11-14 10:28:17,811 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.HACKING_PROTECTION
2024-11-14 10:28:17,812 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.CLEAN_HACKED_EFFECTS
2024-11-14 10:28:20,796 - DEBUG: 13 BLE-Devices found
2024-11-14 10:28:25,627 - ERROR: Exception on request GET /driver/
Traceback (most recent call last):
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\quart\app.py", line 1403, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\quart\app.py", line 1441, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\quart\app.py", line 1029, in handle_user_exception
    raise error
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\quart\app.py", line 1439, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\quart\app.py", line 1535, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\UserInterface\DriverUI.py", line 77, in home_driver
    player_exists, picture, vehicle_information = self._prepare_html_data(player)
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\UserInterface\DriverUI.py", line 357, in _prepare_html_data
    self.environment_mng.put_player_on_next_free_spot(player)
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\EnvironmentManagement\EnvironmentManager.py", line 276, in put_player_on_next_free_spot
    result = self._assign_players_to_vehicles()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\EnvironmentManagement\EnvironmentManager.py", line 301, in _assign_players_to_vehicles
    self.botTest.stop()
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\BotManagement\Bot.py", line 19, in stop
    if self._task:
      ^^^^^^^^^^
AttributeError: 'Bot' object has no attribute '_task'
2024-11-14 10:31:19,615 - INFO: -------------------------
2024-11-14 10:31:19,616 - INFO:  STARTING IAV-Distortion 
2024-11-14 10:31:19,616 - INFO: -------------------------
2024-11-14 10:31:19,632 - INFO: Auto discovery service for Anki cars activated.
2024-11-14 10:31:19,752 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-14 10:31:23,111 - ERROR: post request handler error
Traceback (most recent call last):
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\engineio\async_server.py", line 316, in handle_request
    await socket.handle_post_request(environ)
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\engineio\async_socket.py", line 109, in handle_post_request
    p = payload.Payload(encoded_payload=body)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\engineio\payload.py", line 13, in __init__
    self.decode(encoded_payload)
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\engineio\payload.py", line 44, in decode
    raise ValueError('Too many packets in payload')
ValueError: Too many packets in payload
2024-11-14 10:31:23,377 - ERROR: Invalid transport for session nb8kjcs8lhEx-nmLAAAA (further occurrences of this error will be logged with level INFO)
2024-11-14 10:31:24,747 - DEBUG: 12 BLE-Devices found
2024-11-14 10:31:26,250 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.HACKING_PROTECTION
2024-11-14 10:31:26,252 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.CLEAN_HACKED_EFFECTS
2024-11-14 10:31:29,362 - ERROR: Task exception was never retrieved
future: <Task finished name='Task-193' coro=<Bot.test() done, defined at C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\BotManagement\Bot.py:16> exception=AttributeError("'NoneType' object has no attribute 'get_vehicle_id'")>
Traceback (most recent call last):
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\BotManagement\Bot.py", line 21, in test
    self._behaviour_ctrl.request_speed_change_for(uuid = self.vehicle.get_vehicle_id(), value_perc = 100.0)
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_vehicle_id'
2024-11-14 10:31:34,250 - INFO: Removing player with UUID 91bbb946-a49c-43ce-a0fd-2a71ee20447b from vehicle
2024-11-14 10:31:34,370 - ERROR: Task exception was never retrieved
future: <Task finished name='Task-2016' coro=<DriverUI.__send_proximity_vehicle() done, defined at C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\UserInterface\DriverUI.py:255> exception=AttributeError("'NoneType' object has no attribute 'vehicle_in_proximity'")>
Traceback (most recent call last):
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\UserInterface\DriverUI.py", line 270, in __send_proximity_vehicle
    if previous_vehicle_in_proximity != vehicle.vehicle_in_proximity:
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'vehicle_in_proximity'
2024-11-14 10:31:36,994 - INFO: Removing vehicle with UUID Virtual Vehicle 1
2024-11-14 10:31:44,487 - ERROR: Task exception was never retrieved
future: <Task finished name='Task-6018' coro=<Bot.test() done, defined at C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\BotManagement\Bot.py:16> exception=AttributeError("'NoneType' object has no attribute 'get_vehicle_id'")>
Traceback (most recent call last):
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\BotManagement\Bot.py", line 21, in test
    self._behaviour_ctrl.request_speed_change_for(uuid = self.vehicle.get_vehicle_id(), value_perc = 100.0)
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_vehicle_id'
2024-11-14 10:32:26,396 - INFO: Car Virtual Vehicle 1 doesn't have the effect VehicleEffectIdentification.HACKING_PROTECTION anymore
2024-11-14 10:32:29,771 - DEBUG: 15 BLE-Devices found
2024-11-14 10:33:23,309 - INFO: -------------------------
2024-11-14 10:33:23,311 - INFO:  STARTING IAV-Distortion 
2024-11-14 10:33:23,311 - INFO: -------------------------
2024-11-14 10:33:23,324 - INFO: Auto discovery service for Anki cars activated.
2024-11-14 10:33:23,424 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-14 10:33:24,341 - ERROR: Invalid transport for session 0WcDhw0Y6uAjhUKdAAAA (further occurrences of this error will be logged with level INFO)
2024-11-14 10:33:28,450 - DEBUG: 16 BLE-Devices found
2024-11-14 10:33:34,272 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.HACKING_PROTECTION
2024-11-14 10:33:34,274 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.CLEAN_HACKED_EFFECTS
2024-11-14 10:34:33,461 - DEBUG: 15 BLE-Devices found
2024-11-14 10:34:34,696 - INFO: Car Virtual Vehicle 1 doesn't have the effect VehicleEffectIdentification.HACKING_PROTECTION anymore
2024-11-14 10:38:05,488 - INFO: -------------------------
2024-11-14 10:38:05,489 - INFO:  STARTING IAV-Distortion 
2024-11-14 10:38:05,491 - INFO: -------------------------
2024-11-14 10:38:05,507 - INFO: Auto discovery service for Anki cars activated.
