2024-11-14 10:38:05,611 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-14 10:38:05,739 - ERROR: post request handler error
Traceback (most recent call last):
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\engineio\async_server.py", line 316, in handle_request
    await socket.handle_post_request(environ)
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\engineio\async_socket.py", line 109, in handle_post_request
    p = payload.Payload(encoded_payload=body)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\engineio\payload.py", line 13, in __init__
    self.decode(encoded_payload)
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\engineio\payload.py", line 44, in decode
    raise ValueError('Too many packets in payload')
ValueError: Too many packets in payload
2024-11-14 10:38:05,959 - ERROR: Invalid transport for session mJkdnHsDyta4_lzUAAAA (further occurrences of this error will be logged with level INFO)
2024-11-14 10:38:10,626 - DEBUG: 16 BLE-Devices found
2024-11-14 10:38:25,217 - ERROR: Task exception was never retrieved
future: <Task finished name='Task-429' coro=<Bot.test() done, defined at C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\BotManagement\Bot.py:16> exception=AttributeError("'NoneType' object has no attribute 'speed_request'")>
Traceback (most recent call last):
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\BotManagement\Bot.py", line 21, in test
    self._behaviour_ctrl.request_speed_change_for(uuid = self.vehicle, value_perc = 100.0)
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\VehicleMovementManagement\BehaviourController.py", line 32, in request_speed_change_for
    vehicle.speed_request = value_perc
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'speed_request'
2024-11-14 10:38:42,838 - INFO: Player 91bbb946-a49c-43ce-a0fd-2a71ee20447b timed out. Removing player from the game...
2024-11-14 10:39:15,654 - DEBUG: 19 BLE-Devices found
2024-11-14 10:39:45,190 - INFO: -------------------------
2024-11-14 10:39:45,191 - INFO:  STARTING IAV-Distortion 
2024-11-14 10:39:45,191 - INFO: -------------------------
2024-11-14 10:39:45,207 - INFO: Auto discovery service for Anki cars activated.
2024-11-14 10:39:45,314 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-14 10:39:45,814 - ERROR: Invalid transport for session U1y3KNXNlN1cfIzWAAAA (further occurrences of this error will be logged with level INFO)
2024-11-14 10:39:50,344 - DEBUG: 17 BLE-Devices found
2024-11-14 10:40:12,348 - INFO: Removing player with UUID 91bbb946-a49c-43ce-a0fd-2a71ee20447b from vehicle
2024-11-14 10:40:12,518 - ERROR: Task exception was never retrieved
future: <Task finished name='Task-2224' coro=<DriverUI.__send_proximity_vehicle() done, defined at C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\UserInterface\DriverUI.py:255> exception=AttributeError("'NoneType' object has no attribute 'vehicle_in_proximity'")>
Traceback (most recent call last):
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\UserInterface\DriverUI.py", line 270, in __send_proximity_vehicle
    if previous_vehicle_in_proximity != vehicle.vehicle_in_proximity:
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'vehicle_in_proximity'
2024-11-14 10:40:41,721 - INFO: Player 91bbb946-a49c-43ce-a0fd-2a71ee20447b timed out. Removing player from the game...
2024-11-14 10:40:55,331 - DEBUG: 13 BLE-Devices found
2024-11-14 10:42:38,608 - INFO: -------------------------
2024-11-14 10:42:38,609 - INFO:  STARTING IAV-Distortion 
2024-11-14 10:42:38,610 - INFO: -------------------------
2024-11-14 10:42:38,625 - INFO: Auto discovery service for Anki cars activated.
2024-11-14 10:42:38,786 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-14 10:42:41,697 - ERROR: Invalid transport for session 5VY5_aEdafWUcGDAAAAA (further occurrences of this error will be logged with level INFO)
2024-11-14 10:42:43,802 - DEBUG: 14 BLE-Devices found
2024-11-14 10:43:48,834 - DEBUG: 11 BLE-Devices found
2024-11-14 10:44:53,882 - DEBUG: 14 BLE-Devices found
2024-11-14 11:11:51,377 - INFO: -------------------------
2024-11-14 11:11:51,378 - INFO:  STARTING IAV-Distortion 
2024-11-14 11:11:51,379 - INFO: -------------------------
2024-11-14 11:11:51,396 - INFO: Auto discovery service for Anki cars activated.
2024-11-14 11:11:51,542 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-14 11:11:53,365 - ERROR: post request handler error
Traceback (most recent call last):
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\engineio\async_server.py", line 316, in handle_request
    await socket.handle_post_request(environ)
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\engineio\async_socket.py", line 109, in handle_post_request
    p = payload.Payload(encoded_payload=body)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\engineio\payload.py", line 13, in __init__
    self.decode(encoded_payload)
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\engineio\payload.py", line 44, in decode
    raise ValueError('Too many packets in payload')
ValueError: Too many packets in payload
2024-11-14 11:11:53,649 - ERROR: Invalid transport for session xuLHkbBD5PsRdJ7HAAAA (further occurrences of this error will be logged with level INFO)
2024-11-14 11:11:56,524 - DEBUG: 13 BLE-Devices found
2024-11-14 11:12:31,092 - INFO: -------------------------
2024-11-14 11:12:31,093 - INFO:  STARTING IAV-Distortion 
2024-11-14 11:12:31,095 - INFO: -------------------------
2024-11-14 11:12:31,117 - INFO: Auto discovery service for Anki cars activated.
2024-11-14 11:12:31,236 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-14 11:12:31,611 - ERROR: Invalid transport for session VonoUNCdTUugheePAAAA (further occurrences of this error will be logged with level INFO)
2024-11-14 11:12:36,248 - DEBUG: 18 BLE-Devices found
2024-11-14 11:12:36,252 - ERROR: Task exception was never retrieved
future: <Task finished name='Task-229' coro=<AsyncServer._handle_event_internal() done, defined at C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\socketio\async_server.py:608> exception=AttributeError("'NoneType' object has no attribute 'set_Vehicle'")>
Traceback (most recent call last):
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\socketio\async_server.py", line 610, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\socketio\async_server.py", line 637, in _trigger_event
    ret = await handler(*args)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\UserInterface\StaffUI.py", line 245, in handle_add_virtual_vehicle
    name = environment_mng.add_virtual_vehicle()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\EnvironmentManagement\EnvironmentManager.py", line 677, in add_virtual_vehicle
    self._add_to_active_vehicle_list(new_vehicle, False)
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\EnvironmentManagement\EnvironmentManager.py", line 693, in _add_to_active_vehicle_list
    self._assign_players_to_vehicles()
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\EnvironmentManagement\EnvironmentManager.py", line 301, in _assign_players_to_vehicles
    self.botTest.set_Vehicle(None)
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'set_Vehicle'
2024-11-14 11:12:52,203 - INFO: Removing player with UUID 91bbb946-a49c-43ce-a0fd-2a71ee20447b from vehicle
2024-11-14 11:12:52,316 - ERROR: Task exception was never retrieved
future: <Task finished name='Task-249' coro=<DriverUI.__send_proximity_vehicle() done, defined at C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\UserInterface\DriverUI.py:255> exception=AttributeError("'NoneType' object has no attribute 'vehicle_in_proximity'")>
Traceback (most recent call last):
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\UserInterface\DriverUI.py", line 270, in __send_proximity_vehicle
    if previous_vehicle_in_proximity != vehicle.vehicle_in_proximity:
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'vehicle_in_proximity'
2024-11-14 11:12:53,917 - INFO: Removing vehicle with UUID Virtual Vehicle 1
2024-11-14 11:12:59,286 - INFO: Car Virtual Vehicle 2 now has the effect VehicleEffectIdentification.HACKING_PROTECTION
2024-11-14 11:12:59,287 - INFO: Car Virtual Vehicle 2 now has the effect VehicleEffectIdentification.CLEAN_HACKED_EFFECTS
2024-11-14 11:17:00,341 - INFO: -------------------------
2024-11-14 11:17:00,341 - INFO:  STARTING IAV-Distortion 
2024-11-14 11:17:00,343 - INFO: -------------------------
2024-11-14 11:17:00,353 - INFO: Auto discovery service for Anki cars activated.
2024-11-14 11:17:00,419 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-14 11:17:04,113 - ERROR: Invalid transport for session cx_bSFsqWxyu5o_6AAAA (further occurrences of this error will be logged with level INFO)
2024-11-14 11:17:05,430 - DEBUG: 12 BLE-Devices found
2024-11-14 11:17:08,974 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.HACKING_PROTECTION
2024-11-14 11:17:08,974 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.CLEAN_HACKED_EFFECTS
2024-11-14 11:19:24,671 - INFO: -------------------------
2024-11-14 11:19:24,672 - INFO:  STARTING IAV-Distortion 
2024-11-14 11:19:24,672 - INFO: -------------------------
2024-11-14 11:19:24,681 - INFO: Auto discovery service for Anki cars activated.
2024-11-14 11:19:24,750 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-14 11:19:27,435 - ERROR: Invalid transport for session uD1bdGeDLoaYO7wVAAAA (further occurrences of this error will be logged with level INFO)
2024-11-14 11:19:29,762 - DEBUG: 13 BLE-Devices found
2024-11-14 11:30:26,262 - INFO: -------------------------
2024-11-14 11:30:26,263 - INFO:  STARTING IAV-Distortion 
2024-11-14 11:30:26,264 - INFO: -------------------------
2024-11-14 11:30:26,272 - INFO: Auto discovery service for Anki cars activated.
2024-11-14 11:30:26,382 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-14 11:30:26,589 - ERROR: post request handler error
Traceback (most recent call last):
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\engineio\async_server.py", line 316, in handle_request
    await socket.handle_post_request(environ)
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\engineio\async_socket.py", line 109, in handle_post_request
    p = payload.Payload(encoded_payload=body)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\engineio\payload.py", line 13, in __init__
    self.decode(encoded_payload)
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\engineio\payload.py", line 44, in decode
    raise ValueError('Too many packets in payload')
ValueError: Too many packets in payload
2024-11-14 11:30:26,866 - ERROR: Invalid transport for session YGmzcJcawNyRkEmyAAAA (further occurrences of this error will be logged with level INFO)
2024-11-14 11:30:31,400 - DEBUG: 14 BLE-Devices found
2024-11-14 11:30:34,762 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.HACKING_PROTECTION
2024-11-14 11:30:34,763 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.CLEAN_HACKED_EFFECTS
2024-11-14 11:30:46,585 - INFO: -------------------------
2024-11-14 11:30:46,586 - INFO:  STARTING IAV-Distortion 
2024-11-14 11:30:46,587 - INFO: -------------------------
2024-11-14 11:30:46,597 - INFO: Auto discovery service for Anki cars activated.
2024-11-14 11:30:46,664 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-14 11:30:46,877 - ERROR: Invalid session mQ0zp-6Tq7YkvnBDAAAG (further occurrences of this error will be logged with level INFO)
2024-11-14 11:30:47,187 - ERROR: Invalid transport for session wubM6IgmOuBmAwlZAAAA (further occurrences of this error will be logged with level INFO)
2024-11-14 11:30:51,679 - DEBUG: 13 BLE-Devices found
2024-11-14 11:31:21,566 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.HACKING_PROTECTION
2024-11-14 11:31:21,567 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.CLEAN_HACKED_EFFECTS
2024-11-14 11:31:52,038 - INFO: -------------------------
2024-11-14 11:31:52,038 - INFO:  STARTING IAV-Distortion 
2024-11-14 11:31:52,039 - INFO: -------------------------
2024-11-14 11:31:52,049 - INFO: Auto discovery service for Anki cars activated.
2024-11-14 11:31:52,117 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-14 11:31:53,547 - ERROR: Invalid transport for session oY-VPuUFsTI7gwHbAAAA (further occurrences of this error will be logged with level INFO)
2024-11-14 11:31:57,139 - DEBUG: 16 BLE-Devices found
2024-11-14 11:32:06,511 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.HACKING_PROTECTION
2024-11-14 11:32:06,512 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.CLEAN_HACKED_EFFECTS
2024-11-14 11:33:04,555 - INFO: -------------------------
2024-11-14 11:33:04,555 - INFO:  STARTING IAV-Distortion 
2024-11-14 11:33:04,556 - INFO: -------------------------
2024-11-14 11:33:04,565 - INFO: Auto discovery service for Anki cars activated.
2024-11-14 11:33:04,633 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-14 11:33:06,801 - ERROR: Invalid transport for session DpQJVHDtNYrxw3IsAAAA (further occurrences of this error will be logged with level INFO)
2024-11-14 11:33:09,642 - DEBUG: 18 BLE-Devices found
2024-11-14 11:45:16,916 - INFO: -------------------------
2024-11-14 11:45:16,916 - INFO:  STARTING IAV-Distortion 
2024-11-14 11:45:16,917 - INFO: -------------------------
2024-11-14 11:45:16,926 - INFO: Auto discovery service for Anki cars activated.
2024-11-14 11:45:17,030 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-14 11:45:17,247 - ERROR: post request handler error
Traceback (most recent call last):
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\engineio\async_server.py", line 316, in handle_request
    await socket.handle_post_request(environ)
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\engineio\async_socket.py", line 109, in handle_post_request
    p = payload.Payload(encoded_payload=body)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\engineio\payload.py", line 13, in __init__
    self.decode(encoded_payload)
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\engineio\payload.py", line 44, in decode
    raise ValueError('Too many packets in payload')
ValueError: Too many packets in payload
2024-11-14 11:45:17,388 - ERROR: Invalid transport for session tXrdODfmSAA_lT_IAAAA (further occurrences of this error will be logged with level INFO)
2024-11-14 11:45:22,036 - DEBUG: 13 BLE-Devices found
2024-11-14 11:45:27,420 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.HACKING_PROTECTION
2024-11-14 11:45:27,421 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.CLEAN_HACKED_EFFECTS
2024-11-14 11:45:34,719 - ERROR: Exception on request GET /driver/
Traceback (most recent call last):
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\quart\app.py", line 1403, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\quart\app.py", line 1441, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\quart\app.py", line 1029, in handle_user_exception
    raise error
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\quart\app.py", line 1439, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\quart\app.py", line 1535, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\UserInterface\DriverUI.py", line 77, in home_driver
    player_exists, picture, vehicle_information = self._prepare_html_data(player)
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\UserInterface\DriverUI.py", line 357, in _prepare_html_data
    self.environment_mng.put_player_on_next_free_spot(player)
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\EnvironmentManagement\EnvironmentManager.py", line 277, in put_player_on_next_free_spot
    result = self._assign_players_to_vehicles()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\EnvironmentManagement\EnvironmentManager.py", line 302, in _assign_players_to_vehicles
    self.botTest.set_Vehicle(None)
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'set_Vehicle'
2024-11-14 11:51:49,242 - INFO: -------------------------
2024-11-14 11:51:49,243 - INFO:  STARTING IAV-Distortion 
2024-11-14 11:51:49,243 - INFO: -------------------------
2024-11-14 11:51:49,253 - INFO: Auto discovery service for Anki cars activated.
2024-11-14 11:51:49,325 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-14 11:51:49,618 - ERROR: post request handler error
Traceback (most recent call last):
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\engineio\async_server.py", line 316, in handle_request
    await socket.handle_post_request(environ)
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\engineio\async_socket.py", line 109, in handle_post_request
    p = payload.Payload(encoded_payload=body)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\engineio\payload.py", line 13, in __init__
    self.decode(encoded_payload)
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\engineio\payload.py", line 44, in decode
    raise ValueError('Too many packets in payload')
ValueError: Too many packets in payload
